# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: wytamma.wirth@unimelb.edu.au
author_name: Wytamma Wirth
has_binder: false
has_settings: true
kind: frontend
labextension_name: jupyterlab-cpg-portal-files
project_short_description: Access files on the CPG Portal
python_name: jupyterlab-cpg-portal-files
repository: ''
test: true

